In [21]:
from __future__ import print_function
import torch

In [22]:
x = torch.empty(5,3)
print(x)

tensor([[1.1210e-44, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [23]:
x = torch.rand(5,3)
print(x)

tensor([[0.5575, 0.2770, 0.5611],
        [0.8537, 0.9976, 0.0065],
        [0.2250, 0.2821, 0.2752],
        [0.9344, 0.4274, 0.8130],
        [0.7483, 0.7242, 0.7860]])


In [24]:
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [25]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [26]:
x = x.new_ones(5,3,dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [27]:
x = torch.randn_like(x,dtype=torch.float)
print(x)

tensor([[-0.7339,  0.1282, -0.4095],
        [ 0.9960, -0.0689,  2.0553],
        [-0.5964,  0.9086, -0.7453],
        [-1.0864, -1.6314, -1.0369],
        [-0.5021,  0.1005,  1.8350]])


In [29]:
x.size()

torch.Size([5, 3])

In [30]:
y = torch.rand(5,3)
print(x+y)

tensor([[-0.2545,  0.1474, -0.2569],
        [ 1.2448,  0.1999,  2.6364],
        [-0.5865,  1.5549, -0.4273],
        [-0.6429, -0.8579, -0.4385],
        [ 0.3665,  0.5970,  2.4547]])


In [31]:
print(torch.add(x,y))

tensor([[-0.2545,  0.1474, -0.2569],
        [ 1.2448,  0.1999,  2.6364],
        [-0.5865,  1.5549, -0.4273],
        [-0.6429, -0.8579, -0.4385],
        [ 0.3665,  0.5970,  2.4547]])


In [32]:
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[-0.2545,  0.1474, -0.2569],
        [ 1.2448,  0.1999,  2.6364],
        [-0.5865,  1.5549, -0.4273],
        [-0.6429, -0.8579, -0.4385],
        [ 0.3665,  0.5970,  2.4547]])


In [33]:
y.add_(x)
print(y)

tensor([[-0.2545,  0.1474, -0.2569],
        [ 1.2448,  0.1999,  2.6364],
        [-0.5865,  1.5549, -0.4273],
        [-0.6429, -0.8579, -0.4385],
        [ 0.3665,  0.5970,  2.4547]])


In [34]:
x.t()

tensor([[-0.7339,  0.9960, -0.5964, -1.0864, -0.5021],
        [ 0.1282, -0.0689,  0.9086, -1.6314,  0.1005],
        [-0.4095,  2.0553, -0.7453, -1.0369,  1.8350]])

In [36]:
x.t_() #_ inplace

tensor([[-0.7339,  0.9960, -0.5964, -1.0864, -0.5021],
        [ 0.1282, -0.0689,  0.9086, -1.6314,  0.1005],
        [-0.4095,  2.0553, -0.7453, -1.0369,  1.8350]])

In [43]:
print(x[:,1])

tensor([ 0.9960, -0.0689,  2.0553])


In [46]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [47]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.1710])
-1.1709675788879395


In [49]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [50]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [51]:
a.add_(a)

tensor([2., 2., 2., 2., 2.])

In [53]:
print(a)

tensor([2., 2., 2., 2., 2.])


In [54]:
print(b)

[2. 2. 2. 2. 2.]


In [57]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
